[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "volsegtools"
version = "0.2.5"
authors = [
]
description = ""
readme = "README.md"
requires-python = ">=3.12,<3.13"
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]
dependencies = [
    "dask",
    "dask_image",
    "zarr",
    "numpy",
    "mrcfile",
    "nibabel",
    "pydantic",
    "typer",
    "ciftools",
    "molviewspec>=1.8.1",
    "trimesh>=4.11.5",
    "tifffile>=2024.8.30",
    "h5py>=3.14.0",
    "isort>=6.1.0",
    "pyometiff>=1.0.1",
    "scikit-image>=0.24.0",
    "ome-zarr>=0.10.2",
    "sfftk-rw>=0.8.1",
]

[project.optional-dependencies]
dev = [
    "pytest"
]
vrml = [
    "vrmlxpy",
]

[dependency-groups]
dev = [
    "bumpver>=2026.1132",
    "mypy>=1.19.1",
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.0",
]

[project.scripts]
molstar-preprocessor = 'volsegtools._cli:app'

# -----------------------------------------------------------------------------
# Hatchling Tool configuration
# -----------------------------------------------------------------------------

# Enable the "src" layout of the project
[tool.hatch.build.targets.wheel]
packages = ["src/volsegtools"]

# -----------------------------------------------------------------------------
# Ruff Tool configuration
# -----------------------------------------------------------------------------

[tool.ruff]
target-version = "py313"
line-length = 90 # Does not adhere to PEP-8
src = ["src"]
exclude = [
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "build",
    "dist",
]

[tool.ruff.lint.pycodestyle]
max-line-length = 90

# Lots come from: https://pydevtools.com/handbook/how-to/how-to-configure-recommended-ruff-defaults/
[tool.ruff.lint]
select = [
    "F",      # Pyflakes rules
    "W",      # PyCodeStyle warnings
    "E",      # PyCodeStyle errors
    "I",      # Sort imports properly
    "UP",     # Warn if certain things can changed due to newer Python versions
    "C4",     # Catch incorrect use of comprehensions, dict, list, etc
    "FA",     # Enforce from __future__ import annotations
    "ISC",    # Good use of string concatenation
    "ICN",    # Use common import conventions
    "RET",    # Good return practices
    "SIM",    # Common simplification rules
    "TID",    # Some good import practices
    "TC",     # Enforce importing certain types in a TYPE_CHECKING block
    "PTH",    # Use pathlib instead of os.path
    "NPY",    # Some numpy-specific things
    "FURB",   # Suggest more idiomatic Python patterns
    "B",      # flake8-bugbear
    "PIE",    # flake8-pie
    "RUF",    # Ruff-specific rules
    "N",      # naming
    "S",      # Security
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [ "BLE001", "ANN", "S" ]

[tool.ruff.lint.isort]
known-first-party = ["volsegtools"]
combine-as-imports = true
from-first = true
lines-between-types = 1

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true
mypy-init-return = true
suppress-dummy-args = true

[tool.ruff.lint.flake8-unused-arguments]
ignore-variadic-names = true

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false
docstring-code-format = true
docstring-code-line-length = "dynamic"

# -----------------------------------------------------------------------------
# Pytest Configuration
# -----------------------------------------------------------------------------

[tool.coverage.run]
branch = true
source_pkgs = [ "volsegtools" ]
relative_files = true
data_file = "coverage/internal"

[tool.coverage.report]
show_missing = true
show_context = true
skip_covered = true
skip_empty = true

[tool.coverage.xml]
output = "coverage/coverage.xml"

[tool.coverage.html]
directory = "coverage/html"

# -----------------------------------------------------------------------------
# Bumpver Tool Configuration
# -----------------------------------------------------------------------------

[tool.bumpver]
current_version = "0.2.5"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "chore: Bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = "scripts/pre-bump.sh"
post_commit_hook = ""
commit = true
tag = true
push = false
allowed_branches = "master,main,default,release*"

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    '^version = "{version}"',
    '^current_version = "{version}"',
]
"src/volsegtools/__init__.py" = [
    '__version__ = "{version}"',
]
